USE [master]
GO
/****** Object:  Database [Recipe]    Script Date: 10/1/2014 2:20:57 PM ******/
CREATE DATABASE [Recipe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Recipe', FILENAME = N'd:\sqlserver\data\Recipe.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Recipe_log', FILENAME = N'd:\sqlserver\data\Recipe_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Recipe] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Recipe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Recipe] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Recipe] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Recipe] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Recipe] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Recipe] SET ARITHABORT OFF 
GO
ALTER DATABASE [Recipe] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Recipe] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Recipe] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Recipe] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Recipe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Recipe] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Recipe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Recipe] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Recipe] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Recipe] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Recipe] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Recipe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Recipe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Recipe] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Recipe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Recipe] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Recipe] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Recipe] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Recipe] SET RECOVERY FULL 
GO
ALTER DATABASE [Recipe] SET  MULTI_USER 
GO
ALTER DATABASE [Recipe] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Recipe] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Recipe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Recipe] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [Recipe]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 10/1/2014 2:20:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CustomerId] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Address1] [nvarchar](50) NOT NULL,
	[Address2] [nvarchar](50) NOT NULL,
	[City] [nvarchar](50) NOT NULL,
	[State] [nvarchar](50) NOT NULL,
	[PostalCode] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LineItem]    Script Date: 10/1/2014 2:20:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LineItem](
	[LineItemId] [bigint] IDENTITY(1,1) NOT NULL,
	[OrderId] [bigint] NOT NULL,
	[ProductCode] [nvarchar](50) NOT NULL,
	[Quantity] [int] NOT NULL,
	[Price] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_LineItem] PRIMARY KEY CLUSTERED 
(
	[LineItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Order]    Script Date: 10/1/2014 2:20:57 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[OrderId] [bigint] IDENTITY(1,1) NOT NULL,
	[CustomerId] [bigint] NOT NULL,
	[Tax] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[LineItem]  WITH CHECK ADD  CONSTRAINT [FK_LineItem_Order] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([OrderId])
GO
ALTER TABLE [dbo].[LineItem] CHECK CONSTRAINT [FK_LineItem_Order]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_Order_Customer] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([CustomerId])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_Order_Customer]
GO
USE [master]
GO
ALTER DATABASE [Recipe] SET  READ_WRITE 
GO
